name: "Build and Test"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Python Packages
      shell: bash
      run: pip install build pytest
    - name: Build Python Package
      shell: bash
      run: python -m build .
    - name: Test Python Packages
      shell: bash
      run: |
        #!/bin/bash
        for PKG in dist/*; do
          echo "$PKG"
          pip uninstall -y rapids-dependency-file-generator
          pip install "$PKG"
          pytest
          rapids-dependency-file-generator -h # test CLI output
        done
