branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - addReleases: top
  - - "@semantic-release/exec"
    - verifyReleaseCmd: ./ci/output-release-version.sh ${nextRelease.version}
  - - "@semantic-release/exec"
    - prepareCmd: ./ci/update-versions.sh ${nextRelease.version}
  - - "@semantic-release/exec"
    - publishCmd: ./ci/publish/wheel.sh
  - - "@semantic-release/exec"
    - publishCmd: ./ci/publish/conda.sh rapidsai
  - - "@semantic-release/exec"
    - publishCmd: ./ci/publish/conda.sh rapidsai-nightly
  - - "@semantic-release/git"
    - assets:
        - src/rapids_dependency_file_generator/_version.py
        - src/rapids_dependency_file_generator/schema.json
        - package.json
        - recipe/meta.yaml
