branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - addReleases: top
  - - "@semantic-release/exec"
    - verifyReleaseCmd: ./ci/output-release-version.sh ${nextRelease.version}
  - - "@semantic-release/exec"
    - publishCmd: ./ci/publish/wheel.sh
  - - "@semantic-release/exec"
    - publishCmd: ./ci/publish/conda.sh
  - - "@semantic-release/git"
    - assets:
        - ./**/*
